#!/bin/bash
# store the folder we're coming from, we'll restore this eventually
SCRIPT_BASEFOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# load logging
. $SCRIPT_BASEFOLDER/lib/log.sh
. $SCRIPT_BASEFOLDER/lib/arguments.sh

# ----------------------------------------------------------------------------
# basic setup
# ----------------------------------------------------------------------------
# enables printing of info statements when not 0
VERBOSE=0;

DEPLOY_DIR=/tmp #this will be $HOME after testing
info "this scipt will deploy to this folder: ${DEPLOY_DIR}"

NOW=`date +"%F_%T"` # used to form the backup folder for this run.
BACKUP_FOLDER=$DEPLOY_DIR/backups/$NOW
info "backup folder is: ${BACKUP_FOLDER}"

# think for future profiles feature, not too coasty
DEFAULT_PROFILE=compatible
info "default profile is: $DEFAULT_PROFILE"

PROFILES_FOLDER=$SCRIPT_BASEFOLDER/profiles
info "folder for profiles is: $PROFILES_FOLDER"

# print info for these later
PROFILE=$DEFAULT_PROFILE
info "using profile: $PROFILE"
PROFILE_FOLDER=$PROFILES_FOLDER/$PROFILE
info "using profile folder: $PROFILE_FOLDER"

# ----------------------------------------------------------------------------
# arguments parsing
# ----------------------------------------------------------------------------
while [ "$1" != "" ]
do
    case $1 in
        -t | --target )
            # shift the first part of the argument
            shift
            DEPLOY_DIR=`validate_target $1`
            ;;
        -p | --profile )
            # shift the first part of the argument
            shift
            PROFILE=`validate_profile $1`
            info "using profile: $PROFILE"
            PROFILE_FOLDER=$PROFILES_FOLDER/$PROFILE
            info "using profile folder: $PROFILE_FOLDER"
            ;;
        -v | --verbose )
            VERBOSE=1
            ;;
        -h | --help ) 
            usage
            exit 
            ;;
        * )
            usage_error_exit "illigal option: \"$1\", aborting."
    esac
    # remove the argument from arglist
    shift
done

# ----------------------------------------------------------------------------
# functions to help actually do stuff
# ----------------------------------------------------------------------------
# function to create the backup folder, if existing, does nothing.
function create_backup_folder() {
    if [ ! -d $BACKUP_FOLDER ]; then
        mkdir -p $BACKUP_FOLDER
        info "created backup folder: $BACKUP_FOLDER"
    fi
}

# function to backup the given file
function backup_file ()
{
    # create the backup folder
    create_backup_folder
    
    # if the file is not existing, we don't need to back it up...
    if [ ! -e $1 ]; then
        return 0
    fi

    # if the file is a symlink
    if [ -h $1 ]; then
        warn "backing up symbolic link, this was not the real file."
    fi

    # is the file existing? if so, exist, don't do harmful shit here...
    if [ -e $BACKUP_FOLDER/$1 ]; then
        error "the file $1 was existing in the backup folder. won't go on, would mean we are overriding existing files. do that harm yourself please."
        log "[FAILURE]"
        exit 1
    fi
    cp -i $1 $BACKUP_FOLDER
}

# deploys the file given as argument to $DEPLOY_DIR
function deploy_file () {
    # if the file exists, back it up, no matter what
    backup_file $DEPLOY_DIR/.$1
    # copy the file from profiles folder over to deploy folder
    cp -i $PROFILE_FOLDER/$1 $DEPLOY_DIR/.$1
    if [ $? -eq 1 ]; then
        warn ".$1 NOT deployed"
    else
        info "$PROFILE_FOLDER/$1 deployed to $DEPLOY_DIR/.$1"
    fi
}

# ----------------------------------------------------------------------------
# deploy files for profile
# ----------------------------------------------------------------------------
for file in $PROFILE_FOLDER/* ; do
    deploy_file ${file##*/}
done

log "[SUCCESS]"
# correctly exist the program with the last commands exit code.
exit
